core/urls.py
from django.urls import path

from core.views import index

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
]

lms/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from students.views import (
    get_random,
    hello,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', hello),
    path('password/', get_random),

    path('', include('core.urls')),

    path('students/', include('students.urls')),

    path('teachers/', include('teachers.urls')),

    path('groups/', include('groups.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

students/urls.py
from django.urls import path

from students.views import (
    edit_student,
    create_student,
    get_students,
    delete_student,
)

app_name = 'students'

urlpatterns = [
    path('', get_students, name='list'),
    path('create/', create_student, name='create'),
    path('edit/<uuid:uuid>', edit_student, name='edit'),
    path('delete/<uuid:uuid>', delete_student, name='delete'),
]

students/models.py
import datetime
import random

from django.db import models

from faker import Faker

from groups.models import Group

import uuid

class Student(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    first_name = models.CharField(max_length=64, null=False)
    last_name = models.CharField(max_length=84, null=False)
    birthdate = models.DateTimeField(null=True, default=datetime.date.today)
    rating = models.SmallIntegerField(null=True, default=0)
    email = models.EmailField(null=True, max_length=128)
    phone_number = models.CharField(null=True, max_length=16)
    group = models.ForeignKey(
        to=Group,
        null=True,
        on_delete=models.SET_NULL,
        related_name='students'
    )


    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        return f'{self.id}, {self.full_name()}, {self.rating}'

    @staticmethod
    def generate_students(count):

        faker = Faker()

        for _ in range(count):
            st = Student.objects.screate(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                rating=random.randint(0, 100),
                phone_number=str(faker.phone_number()),
            )
            st.save()

students/forms.py
from django import forms

from students.models import Student


class StudentCreateForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['first_name', 'last_name', 'rating']

students/views.py
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from students.forms import StudentCreateForm
from students.models import Student
from students.utils import gen_password, parse_length


def hello(request):
    return HttpResponse('Hello from Django!')


def get_random(request):
    try:
        length = parse_length(request, 10)
    except Exception as ex:
        return HttpResponse(str(ex), status_code=400)

    result = gen_password(length)

    return HttpResponse(result)


def get_students(request):
    students = Student.objects.all()

    first_name = request.GET.get('first_name')
    last_name = request.GET.get('last_name')
    rating = request.GET.get('rating')

    if first_name:
        or_names = first_name.split('|')
        or_cond = Q()
        for or_name in or_names:
            or_cond = or_cond | Q(first_name=or_name)
        students = students.filter(or_cond)

    if last_name:
        students = students.filter(last_name=last_name)

    if rating:
        students = students.filter(rating=rating)

    return render(
        request=request,
        template_name='students-list.html',
        context={
            'students': students
        }

    )


def create_student(request):

    if request.method == 'GET':

        form = StudentCreateForm()

    elif request.method == 'POST':

        form = StudentCreateForm(request.POST)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('students:list'))

    return render(
        request=request,
        template_name='students-create.html',
        context={
            'form': form
        }
    )



def edit_student(request, uuid):

    try:
        student = Student.objects.get(uuid=uuid)
    except Student.DoesNotExist:
        return HttpResponse("Student doesn't exist", status=404)

    if request.method == 'GET':

        form = StudentCreateForm(instance=student)

    elif request.method == 'POST':

        form = StudentCreateForm(
            data=request.POST,
            instance=student
        )

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('students:list'))

    return render(
        request=request,
        template_name='students-edit.html',
        context={
            'form': form,
            'student': student
        }
    )



def delete_student(request, uuid):
    student = get_object_or_404(Student, uuid=uuid)
    student.delete()
    return HttpResponseRedirect(reverse('students:list'))

students/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>   😜   </title>
    <link rel="shortcut icon" type="image/png" href="{% static 'icons/favicon.ico' %}"/>
    {% block style %}
    <style>
        .header {
            height: 80px;
            background: #101010;
            color: aqua;
        }
        .content {
            width: 250px;
            height: 1600px;
            background: #141414;
            margin-top: 10px;
        }
        .text {
            color: aqua;
            margin-top: 20px;
            font-family: monospace;
            font-size: 14px;
            text-decoration: none;
        }
        .background_button {
            background: #4bff00;
            padding: 7px 10px;
            color: white;
            text-decoration: unset;
            border-radius: 10px;
            font-size: 15px;
            font-family: monospace;
        }
        .button {
            background:#000000;
            border: none;
            border-radius: 15px;
            color: white;
            padding: 5px 10px;
            text-decoration: none;
            cursor: pointer;
            font-size: 15px;
            font-family: monospace;"
        }
    </style>
    {% endblock %}
</head>
<body style="background: #323232">
<div class="header">
    <h1>
        <a href="{% url 'core:index' %}" style="
            padding: 5px 10px;
            color: aqua;
            text-decoration: unset;
            border-radius: 10px;
            font-size: 56px;
            font-family: monospace;
            margin-left: 20px;
            margin-top: 20px;
            " >LMS</a>
    </h1>
</div>

{% block content %}
{% endblock %}

</body>
</html>

students/templates/students-create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create student</title>
</head>
<body style="background-image:url(https://w-dog.ru/wallpapers/15/12/478495727685011.jpg)">

    <form method="post">

        {% csrf_token %}

        {{form.as_p}}

        <input type="submit" value="Create">
    </form>

</body>
</html>

students/templates/students-edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>😜</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'icons/favicon.ico' %}"/>
    <style>
        .header {
            height: 80px;
            background: #101010;
            color: aqua;
        }
        .content {
            width: 200px;
            height: 1600px;
            background: #141414;
            color: aqua;
            margin-top: 20px;
        }
        .background_button {
            background: #4bff00;
            padding: 7px 10px;
            color: white;
            text-decoration: unset;
            border-radius: 10px;
            font-size: 15px;
            font-family: monospace;
        }.button {
            background:#000000;
            border: none;
            border-radius: 15px;
            color: white;
            padding: 5px 10px;
            text-decoration: none;
            cursor: pointer;
            font-size: 15px;
            font-family: monospace;"
        }
    </style>
</head>
<body>

    <form method="post">

        {% csrf_token %}

        {{form.as_p}}

        <div class="background_button">
            <input
                class="button" type="submit" value="Save">
            <a href="{% url 'students:delete' student.uuid %}" class="button" >Delete</a>
        </div>
    </form>

</body>
</html>

students/templates/students-list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>😜</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'icons/favicon.ico' %}"/>
    <style>
        .header {
            height: 80px;
            background: #101010;
            color: aqua;
        }
        .content {
            width: 250px;
            height: 1600px;
            background: #141414;
            margin-top: 10px;
        }
        .text {
            color: aqua;
            margin-top: 20px;
            font-family: monospace;
            font-size: 14px;
            text-decoration: none;
        }
        .background_button {
            background: aqua;
            {##4bff00#}
            padding: 7px 10px;
            color: white;
            text-decoration: unset;
            border-radius: 10px;
            font-size: 15px;
            font-family: monospace;
        }
        .button {
            background:#000000;
            border: none;
            border-radius: 15px;
            color: white;
            padding: 5px 10px;
            text-decoration: none;
            cursor: pointer;
            font-size: 15px;
            font-family: monospace;"
        }
    </style>
</head>
<body style="background: #323232">

<div class="header">
    <h1>
        <a href="{% url 'core:index' %}" style="
            padding: 5px 10px;
            color: aqua;
            text-decoration: unset;
            border-radius: 10px;
            font-size: 56px;
            font-family: monospace;
            margin-left: 20px;
            margin-top: 20px;
            " >LMS</a>
    </h1>
</div>

<div style="color: aqua; background: #141414" align = "center";>
    <form>
      <label >First name:</label>   
      <input class="button" type="text" name="first_name"><br><br>

      <label>Last name:</label>
      <input type="text" name="last_name" class="button"><br><br>

      <label>Rating:</label>
      <input class="button" type="number" name="rating" min="0" max="100"><br>

      <div class="background_button">
      <a href="{% url 'students:create'%}">
        <input type="button" value="Create" class="button">

        <input type="submit" value="Search" class="button">
      </div>
    </form>

</div>

<div align = "center">
    <div class="content">
        {% for student in students %}
            <a href="{% url 'students:edit' student.uuid %}"
            class="text" >
{#            {{ student.id }}#}
            {{ student.first_name }}
            {{ student.last_name }}
            {{ student.rating }}</a>
            <br>
        {% endfor %}
    </div>
</div>

</body>

</html>