core/urls.py
from django.urls import path

from core.views import index

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
]

groups/urls.py
from django.urls import path

from groups.views import (
    edit_group,
    create_group,
    get_groups,
    delete_group,
)

app_name = 'groups'

urlpatterns = [
    path('', get_groups, name='list'),
    path('create/', create_group, name='create'),
    path('edit/<int:id>', edit_group, name='edit'),
    path('delete/<int:id>', delete_group, name='delete'),
]

lms/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from students.views import (
    get_random,
    hello,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', hello),
    path('password/', get_random),

    path('', include('core.urls')),

    path('students/', include('students.urls')),

    path('teachers/', include('teachers.urls')),

    path('groups/', include('groups.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

groups/models.py
from django.db import models

from faker import Faker


class Group(models.Model):
    name = models.CharField(max_length=64, null=False)
    number_of_students = models.SmallIntegerField(max_length=64, null=False)


    def __str__(self):
        return f'{self.name}, {self.number_of_students}'

    @staticmethod
    def generate_group(count):
        faker = Faker()

        for _ in range(count):
            group = Group.objects.create(
                name=faker.first_name(),
            )
            group.save()

groups/forms.py
from django import forms

from groups.models import Group


class GroupsCreateForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name', 'number_of_students']

groups/views.py
from django.db.models import Q
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from groups.forms import GroupsCreateForm
from groups.models import Group


def get_groups(request):
    groups = Group.objects.all()

    name = request.GET.get('name')
    number_of_students = request.GET.get('rating')

    if name:
        or_names = name.split('|')
        or_cond = Q()
        for or_name in or_names:
            or_cond = or_cond | Q(name=or_name)
        groups = groups.filter(or_cond)

    if number_of_students:
        groups = groups.filter(number_of_students=number_of_students)

    return render(
        request=request,
        template_name='groups-list.html',
        context={
            'groups': groups
        }

    )


def create_group(request):

    if request.method == 'GET':

        form = GroupsCreateForm()

    elif request.method == 'POST':

        form = GroupsCreateForm(request.POST)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/groups/')

    return render(
        request=request,
        template_name='Groups-create.html',
        context={
            'form': form
        }
    )


def edit_group(request, id):

    try:
        group = Group.objects.get(id=id)
    except Group.DoesNotExist:
        return HttpResponse("Group doesn't exist", status=404)

    if request.method == 'GET':

        form = GroupsCreateForm(instance=group)

    elif request.method == 'POST':

        form = GroupsCreateForm(
            data=request.POST,
            instance=group
        )

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('groups:list'))

    return render(
        request=request,
        template_name='groups-edit.html',
        context={
            'form': form,
            'groups': group
        }
    )


def delete_group(request, id):
    group = get_object_or_404(Group, id=id)
    group.delete()
    return HttpResponseRedirect(reverse('groups:list'))

groups/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
{% block title %}
        <title>LMS</title>
{% endblock %}
{% block link %}
    <link rel="shortcut icon" type="image/png" href="{% static 'icons/favicon.ico' %}"/>
{% endblock %}
{% block style %}
    <style>
        .header {
            height: 80px;
            background: #101010;
            color: aqua;
        }
        .content {
            width: 250px;
            height: 1600px;
            background: #141414;
            margin-top: 10px;
        }
        .text {
            color: aqua;
            margin-top: 20px;
            font-family: monospace;
            font-size: 14px;
            text-decoration: none;
        }
        .background_button {
            background: aqua;
            {##4bff00#}
            padding: 7px 10px;
            color: white;
            text-decoration: unset;
            border-radius: 10px;
            font-size: 15px;
            font-family: monospace;
        }
        .button {
            background:#000000;
            border: none;
            border-radius: 15px;
            color: white;
            padding: 5px 10px;
            text-decoration: none;
            cursor: pointer;
            font-size: 15px;
            font-family: monospace;"
        }
    </style>
{% endblock %}

</head>
<body style="background: #323232">

<div>
    <a style="font-family: Roboto; font-size: 56px" href="{% url 'core:index' %}">LMS</a>
</div>


{% block icon %}
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
{% endblock %}

</body>
</html>

groups/templates/groups-create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create groups</title>
</head>
<body style="background-image:url(https://w-dog.ru/wallpapers/15/12/478495727685011.jpg)">

    <form method="post">

        {% csrf_token %}

        {{form.as_p}}

        <input type="submit" value="Create">
    </form>

</body>
</html>

groups/templates/groups-edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>😜</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'icons/favicon.ico' %}"/>
    <style>
        .header {
            height: 80px;
            background: #101010;
            color: aqua;
        }
        .content {
            width: 200px;
            height: 1600px;
            background: #141414;
            color: aqua;
            margin-top: 20px;
        }
        .background_button {
            background: #4bff00;
            padding: 7px 10px;
            color: white;
            text-decoration: unset;
            border-radius: 10px;
            font-size: 15px;
            font-family: monospace;
        }.button {
            background:#000000;
            border: none;
            border-radius: 15px;
            color: white;
            padding: 5px 10px;
            text-decoration: none;
            cursor: pointer;
            font-size: 15px;
            font-family: monospace;"
        }
    </style>
</head>
<body>

    <form method="post">

        {% csrf_token %}

        {{form.as_p}}

        <div class="background_button">
            <input
                class="button" type="submit" value="Save">
            <a href="{% url 'groups:delete' groups.id %}" class="button" >Delete</a>
        </div>
    </form>

</body>
</html>

groups/templates/groups-list.html
{% extends 'base.html' %}

{#{% include 'base.html' %}#}

{% block icon %}
<div class="header">
    <h1>
        <a href="{% url 'core:index' %}" style="
            padding: 5px 10px;
            color: aqua;
            text-decoration: unset;
            border-radius: 10px;
            font-size: 56px;
            font-family: monospace;
            margin-left: 20px;
            margin-top: 20px;
            " >LMS</a>
    </h1>
</div>
{% endblock %}

{#{% block style %}#}
{#    {{ block.super }}#}
{#{% endblock %}#}

{% block header %}
<div style="color: aqua; background: #141414" align = "center";>
    <form>
      <label >Name:</label>
      <input class="button" type="text" name="first_name"><br><br>

      <label>Number of students:</label>
      <input type="text" name="last_name" class="button"><br><br>

      <div class="background_button">
      <a href="{% url 'groups:create'%}">
        <input type="button" value="Create" class="button">

        <input type="submit" value="Search" class="button">
      </div>
    </form>

</div>
{% endblock %}

{% block content %}

<div align = "center">
    <div class="content">
        {% for group in groups %}
            <a href="{% url 'groups:edit' group.id %}"
            class="text" >
            {{ group.name }}
            {{ group.number_of_students }}
            </a>
            <br>
        {% endfor %}
    </div>
</div>
{% endblock %}