core/urls.py
from django.urls import path

from core.views import index

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
]

lms/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from students.views import (
    get_random,
    hello,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', hello),
    path('password/', get_random),

    path('', include('core.urls')),

    path('students/', include('students.urls')),

    path('teachers/', include('teachers.urls')),

    path('groups/', include('groups.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

students/urls.py
from django.urls import path

from students.views import (
    edit_student,
    create_student,
    get_students,
    delete_student,
)

app_name = 'students'

urlpatterns = [
    path('', get_students, name='list'),
    path('create/', create_student, name='create'),
    path('edit/<uuid:uuid>', edit_student, name='edit'),
    path('delete/<uuid:uuid>', delete_student, name='delete'),
]

teachers/urls.py
from django.urls import path

from teachers.views import (
    edit_teacher,
    create_teacher,
    get_teachers,
    delete_teacher,
)

app_name = 'teachers'

urlpatterns = [
    path('', get_teachers, name='list'),
    path('create/', create_teacher, name='create'),
    path('edit/<int:id>', edit_teacher, name='edit'),
    path('delete/<int:id>', delete_teacher, name='delete'),

]

teachers/models.py
from django.db import models

from faker import Faker


class Teachers(models.Model):
    first_name = models.CharField(max_length=64, null=False)
    last_name = models.CharField(max_length=84, null=False)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    @staticmethod
    def generate_teachers(count):
        faker = Faker()

        for _ in range(count):
            teacher = Teachers.objects.create(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
            )
            teacher.save()

teachers/forms.py
from django import forms

from teachers.models import Teachers


class TeachersCreateForm(forms.ModelForm):
    class Meta:
        model = Teachers
        fields = ['first_name', 'last_name']

teachers/views.py
from django.db.models import Q
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from teachers.forms import TeachersCreateForm
from teachers.models import Teachers


def create_teacher(request):

    if request.method == 'GET':

        form = TeachersCreateForm()

    elif request.method == 'POST':

        form = TeachersCreateForm(request.POST)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/teachers/')

    return render(
        request=request,
        template_name='teachers-create.html',
        context={
            'form': form
        }
    )


def get_teachers(request):
    teachers = Teachers.objects.all()

    first_name = request.GET.get('first_name')
    last_name = request.GET.get('last_name')
    rating = request.GET.get('rating')

    if first_name:
        or_names = first_name.split('|')
        or_cond = Q()
        for or_name in or_names:
            or_cond = or_cond | Q(first_name=or_name)
        teachers = teachers.filter(or_cond)

    if last_name:
        teachers = teachers.filter(last_name=last_name)

    if rating:
        teachers = teachers.filter(rating=rating)

    return render(
        request=request,
        template_name='teachers-list.html',
        context={
            'teachers': teachers
        }

    )


def edit_teacher(request, id):

    try:
        teacher = Teachers.objects.get(id=id)
    except Teachers.DoesNotExist:
        return HttpResponse("Teacher doesn't exist", status=404)

    if request.method == 'GET':

        form = TeachersCreateForm(instance=teacher)

    elif request.method == 'POST':

        form = TeachersCreateForm(
            data=request.POST,
            instance=teacher
        )

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('teachers:list'))

    return render(
        request=request,
        template_name='teacher-edit.html',
        context={
            'form': form,
            'teachers': teacher
        }
    )


def delete_teacher(request, id):
    teacher = get_object_or_404(Teachers, id=id)
    teacher.delete()
    return HttpResponseRedirect(reverse('teachers:list'))

teachers/templates/teacher-edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>😜</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'icons/favicon.ico' %}"/>
    <style>
        .header {
            height: 80px;
            background: #101010;
            color: aqua;
        }
        .content {
            width: 200px;
            height: 1600px;
            background: #141414;
            color: aqua;
            margin-top: 20px;
        }
        .background_button {
            background: #4bff00;
            padding: 7px 10px;
            color: white;
            text-decoration: unset;
            border-radius: 10px;
            font-size: 15px;
            font-family: monospace;
        }.button {
            background:#000000;
            border: none;
            border-radius: 15px;
            color: white;
            padding: 5px 10px;
            text-decoration: none;
            cursor: pointer;
            font-size: 15px;
            font-family: monospace;"
        }
    </style>
</head>
<body>

    <form method="post">

        {% csrf_token %}

        {{form.as_p}}

        <div class="background_button">
            <input class="button" type="submit" value="Save">
            <a href="{% url 'teachers:delete' teachers.id %}" class="button" >Delete</a>
        </div>
    </form>

</body>
</html>

teachers/templates/teachers-create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create teachers</title>
</head>
<body style="background-image:url(https://w-dog.ru/wallpapers/15/12/478495727685011.jpg)">

    <form method="post">

        {% csrf_token %}

        {{form.as_p}}

        <input type="submit" value="Create">
    </form>

</body>
</html>

teachers/templates/teachers-list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>😜</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'icons/favicon.ico' %}"/>
    <style>
        .header {
            height: 80px;
            background: #101010;
            color: aqua;
        }
        .content {
            width: 250px;
            height: 1600px;
            background: #141414;
            margin-top: 10px;
        }
        .text {
            color: aqua;
            margin-top: 20px;
            font-family: monospace;
            font-size: 14px;
            text-decoration: none;
        }
        .background_button {
            background: aqua;
            {##4bff00#}
            padding: 7px 10px;
            color: white;
            text-decoration: unset;
            border-radius: 10px;
            font-size: 15px;
            font-family: monospace;
        }
        .button {
            background:#000000;
            border: none;
            border-radius: 15px;
            color: white;
            padding: 5px 10px;
            text-decoration: none;
            cursor: pointer;
            font-size: 15px;
            font-family: monospace;"
        }
    </style>
</head>
<body style="background: #323232">

<div class="header">
    <h1>
        <a href="{% url 'core:index' %}" style="
            padding: 5px 10px;
            color: aqua;
            text-decoration: unset;
            border-radius: 10px;
            font-size: 56px;
            font-family: monospace;
            margin-left: 20px;
            margin-top: 20px;
            " >LMS</a>
    </h1>
</div>

<div style="color: aqua; background: #141414" align = "center";>
    <form>
      <label >First name:</label>
      <input class="button" type="text" name="first_name"><br><br>

      <label>Last name:</label>
      <input type="text" name="last_name" class="button"><br><br>

      <label>Rating:</label>
      <input class="button" type="number" name="rating" min="0" max="100"><br>

      <div class="background_button">
      <a href="{% url 'students:create'%}">
        <input type="button" value="Create" class="button">

        <input type="submit" value="Search" class="button">
      </div>
    </form>

</div>

<div align = "center">
    <div class="content">
        {% for teachers in teachers %}
            <a href="{% url 'teachers:edit' teachers.id %}"
            class="text" >
            {{ teachers.id }}
            {{ teachers.first_name }}
            {{ teachers.last_name }}</a>
            <br>
        {% endfor %}
    </div>
</div>

</body>

</html>