core/urls.py
from django.urls import path

from core.views import index

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
]

groups/urls.py
from django.urls import path

from groups.views import (
    edit_group,
    create_group,
    get_groups,
    delete_group,
)

app_name = 'groups'

urlpatterns = [
    path('', get_groups, name='list'),
    path('create/', create_group, name='create'),
    path('edit/<int:id>', edit_group, name='edit'),
    path('delete/<int:id>', delete_group, name='delete'),
]

lms/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from students.views import (
    get_random,
    hello,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', hello),
    path('password/', get_random),

    path('', include('core.urls')),

    path('students/', include('students.urls')),

    path('teachers/', include('teachers.urls')),

    path('groups/', include('groups.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

students/urls.py
from django.urls import path

from students.views import (
    edit_student,
    create_student,
    get_students,
    delete_student,
)

app_name = 'students'

urlpatterns = [
    path('', get_students, name='list'),
    path('create/', create_student, name='create'),
    path('edit/<uuid:uuid>', edit_student, name='edit'),
    path('delete/<uuid:uuid>', delete_student, name='delete'),
]

teachers/urls.py
from django.urls import path

from teachers.views import (
    edit_teacher,
    create_teacher,
    get_teachers,
    delete_teacher,
)

app_name = 'teachers'

urlpatterns = [
    path('', get_teachers, name='list'),
    path('create/', create_teacher, name='create'),
    path('edit/<int:id>', edit_teacher, name='edit'),
    path('delete/<int:id>', delete_teacher, name='delete'),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>.   😜   .</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'icons/favicon.ico' %}"/>
    <style>
        .header {
            height: 80px;
            background: #101010;
            color: aqua;
        }
    </style>
{#{% block title %}#}
{#        <title>LMS</title>#}
{#{% endblock %}#}
</head>
<body style="background: #323232">

<div class="header">
    <h1>
        <a href="{% url 'core:index' %}" style="
            padding: 5px 10px;
            color: aqua;
            text-decoration: unset;
            border-radius: 10px;
            font-size: 56px;
            font-family: monospace;
            margin-left: 20px;
            margin-top: 20px;
            " >LMS</a>
    </h1>
</div>

{% block content %}
{% endblock %}

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <br><br>
    <a style="background:#000000;
            border: none;
            border-radius: 15px;
            color: white;
            padding: 5px 10px;
            text-decoration: none;
            cursor: pointer;
            font-size: 15px;
            font-family: monospace;" href="{% url 'students:list' %}">➤ Students list</a><br><br>
    <a style="background:#000000;
            border: none;
            border-radius: 15px;
            color: white;
            padding: 5px 10px;
            text-decoration: none;
            cursor: pointer;
            font-size: 15px;
            font-family: monospace;" href="{% url 'students:create' %}">➤ Student create</a><br><br><br><br>
    <a style="background:#000000;
            border: none;
            border-radius: 15px;
            color: white;
            padding: 5px 10px;
            text-decoration: none;
            cursor: pointer;
            font-size: 15px;
            font-family: monospace;" href="{% url 'teachers:list' %}">➤ Teachers list</a><br><br>
    <a style="background:#000000;
            border: none;
            border-radius: 15px;
            color: white;
            padding: 5px 10px;
            text-decoration: none;
            cursor: pointer;
            font-size: 15px;
            font-family: monospace;" href="{% url 'teachers:create' %}">➤ Teacher create</a><br><br><br><br>
    <a style="background:#000000;
            border: none;
            border-radius: 15px;
            color: white;
            padding: 5px 10px;
            text-decoration: none;
            cursor: pointer;
            font-size: 15px;
            font-family: monospace;" href="{% url 'groups:list' %}">➤ Groups list</a><br><br>
    <a style="background:#000000;
            border: none;
            border-radius: 15px;
            color: white;
            padding: 5px 10px;
            text-decoration: none;
            cursor: pointer;
            font-size: 15px;
            font-family: monospace;" href="{% url 'groups:create' %}">➤ Group create</a><br><br><br><br>
{% endblock %}